### ISSUE TITLE
[All connections / Server Manager / etc ] - Search result count updates, but results not displayed

### ISSUE THREAD

**Issue by tbakrf** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#139] opened 2022-03-11 20:59 UTC
2110: 1.3.2111.01001

**To Reproduce**
1. Go to "All connections" or any connections list (e.g.) /servermanager/connections
2. Note that non-filtered, existing connections are displayed
3. Note to the left of the search bar, you will see result count (e.g.) "506 items"
4. Click in search field and type part of the host names (e.g.) "9th"
5. Note number of results changes (e.g. 5 items) - but no results are displayed (list is empty)
6. Clear out search field - results remain empty, count goes back to original (e.g. "506 items")
7. Toggle between "all connections" and "server manager" etc. to reload unfiltered list

**Expected behavior**
Filtered results should be displayed

**Screenshots & Additional context**
![2](https://user-images.githubusercontent.com/15786305/157964498-d5746dc4-1fd2-4cd7-b5fc-9c3017f3ae31.png)
![1](https://user-images.githubusercontent.com/15786305/157964500-2805cbe2-a7fe-459e-b613-e5775a8740a0.png)

**Comment by trungtran-msft** [comment] 2022-03-14 17:40
Hey @tbakrf, this is a known issue with version 2110. We are releasing a public preview this Wednesday that you can try out. This build will have the fix in it.

**Comment by trungtran-msft** [comment] 2022-03-15 23:54
Hello, our release is going to be delayed. In the meantime, you can try this private build with the fix.

Please understand that this build is not supported. We are still working on fixes and validation before the official GA.

Here is the build: https://microsoft-my.sharepoint-df.com/:u:/p/praror/EV_E1yve_b1KvHxkpTE3_YkBGfda_SMqMVCkNibjEi6h_g?e=4IEzpg&isSPOFile=1

**Comment by tbakrf** [comment] 2022-03-16 12:35
Thanks - works as suggested / nice job!  Looking forward to the official GA!

**Comment by RebeccaMbulaMs** [comment] 2022-05-09 09:18
Hey @tbakrf :)

My name is Rebecca, Product Manager on Windows Admin Center.

Here is a link to our 2110.2 GA notes: https://techcommunity.microsoft.com/t5/windows-admin-center-blog/windows-admin-center-version-2110-2-is-now-in-public-preview/ba-p/3263839?msclkid=75816bf0cf7811eca0bce203a2d3fde2

I wanted to inquire if you are still facing this issue or if the issue regressed on your end?

Kind regards!

**Comment by tbakrf** [comment] 2022-05-09 13:56
Here's what I was showing up until your comment:
Current: Version (1.3.2202.21001)
New: Version (1.3.2204.19002)

(Current version was the unsupported one from trungtran-msft, which fixed the bug)
I just updated to the new version and can confirm the bug is still fixed / the search results are (still) working as intended.
Thanks!!

**Comment by RebeccaMbulaMs** [comment] 2022-05-09 14:01
Great! 
Glad to hear that you could access the link and that the issue is still fixed.
Closing this issue. Please continue to feel free to log any issues you may be facing!
Kind regards!

**Closed by RebeccaMbulaMs** 2022-05-09 14:01 UTC
Labels: bug

**Comment by tbakrf** [comment] 2022-05-23 13:41
Rebecca,

We get this error in current WAC trying to connect to a host after the in-place upgrade
Version
2110.2
Build
1.3.2204.19002


"WinRM cannot process the request. The following error with error code 0x8009030e occurred while using Negotiate authentication: A specified logon session does not exist."

I was under the impression that we were using Kerberos / we had not turned on WinRM over HTTPS (we didn't figure out how to configure that).
Can you confirm if the error we are getting is due to having WinRM over HTTPS turned on in WAC?

Thanks!




Todd Biggins
Applications Management

***@***.******@***.***> | www.akrf.com<https://www.akrf.com/> <https://www.akrf.com/>
440 Park Avenue South, 7th Floor, New York, NY 10016



________________________________

**Comment by tbakrf** [comment] 2022-05-24 12:56
Disregard - FYI I simply did a full uninstall / reinstall with the latest WAC msi / things are working fine.




Todd Biggins
Applications Management

***@***.******@***.***> | www.akrf.com<https://www.akrf.com/> <https://www.akrf.com/>
440 Park Avenue South, 7th Floor, New York, NY 10016



________________________________
