### ISSUE TITLE
Unable to list file shares

### ISSUE THREAD

**Issue by teddimitrov** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#8] opened 2021-07-23 13:43 UTC
Using the latest version of the Files & file sharing extension - 1.240.0 and unable to list server file shares... Others are [reporting the issue](https://docs.microsoft.com/en-us/answers/questions/460580/windows-admin-center-file-shares.html) as well...

**Comment by trungtran-msft** [comment] 2021-07-28 22:00
Hey @teddimitrov, 

I believe this is fixed in the latest extension version of 1.242.0. I am not able to reproduce this issue, can you please confirm on your environment?

Thank you, 
Trung

**Comment by teddimitrov** [comment] 2021-07-29 13:18
@trungtran-msft 

Yes, I can confirm that the updated extension v. 1.241.0  (I don't see 1.242.0 yet as available) does indeed fix the issue. Thank you!

**Comment by trungtran-msft** [comment] 2021-07-30 16:55
@teddimitrov 

Amazing, thank you so much :)
I'll close out this issue now.

**Closed by trungtran-msft** 2021-07-30 16:55 UTC
